version: '3'
services:
   client:
        container_name: telegraph_client_1
        build: ./client
        image: telegraph-client
        ports:
          - 8080:8080
        working_dir: /code
        volumes:
          - type: bind
            source: ./client
            target: /code
        command: ["http-server"]

   server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=telegraph
      - DB_CONNECTION=mongodb://futureproof:telegraphpass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"

   db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=futureproof
      - MONGO_INITDB_DATABASE=telegraph
      - MONGO_INITDB_ROOT_PASSWORD=telegraphpass
volumes:
  dbdata: